title: Mihir Rane # your name (or website title) here
logo: "/images/0.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Grad student @ University of Texas at Dallas
  <br><br>
  Machine learning - Data Science - Software Development
  <br><br>
  <a href="https://www.linkedin.com/in/mihirrane/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
